default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: engli_development

test:
  <<: *default
  database: engli_test

production:
  <<: *default
  database: engli_production
  username: engli
  password: <%= ENV['ENGLI_DATABASE_PASSWORD'] %>
